name: ml_kit_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.2
  path_provider: ^2.1.0
  google_mlkit_commons: ^0.6.1
  google_mlkit_barcode_scanning: ^0.10.0
  google_mlkit_digital_ink_recognition: ^0.10.0
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_face_mesh_detection: ^0.0.2
  google_mlkit_image_labeling: ^0.10.0
  google_mlkit_object_detection: ^0.11.0
  google_mlkit_pose_detection:
  google_mlkit_selfie_segmentation:
  google_mlkit_text_recognition:
  google_mlkit_entity_extraction:
  google_mlkit_language_id:
  google_mlkit_translation:
  google_mlkit_smart_reply:
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ml/
    - assets/images/
  